# Generated by Django 4.2.21 on 2025-06-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('mobile', models.CharField(max_length=15)),
                ('report', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
    ]
