# Generated by Django 4.2.21 on 2025-06-19 13:58

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to=patients.models.patient_report_upload_path),
        ),
    ]
