# Generated by Django 4.2.21 on 2025-06-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_report_medicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
