# Generated by Django 4.2.21 on 2025-06-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_medicalreport_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='advice',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='observations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
