# Generated by Django 4.2.23 on 2025-06-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicalreport_advice_medicalreport_observations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalreport',
            old_name='advice',
            new_name='advise',
        ),
    ]
