# Generated by Django 4.2.23 on 2025-06-23 05:14

from django.db import migrations, models
import patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_medicalreport_report_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report_file',
            field=models.FileField(upload_to=patients.models.patient_report_upload_path),
        ),
    ]
