# Generated by Django 4.2.23 on 2025-06-23 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_medicalreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
